version: 0.2

phases:
    install:
        runtime-versions:
            docker: 18
        commands:
            # - $(aws ecr get-login --no-include-email --region ap-northeast-2)
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws --version
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            - echo Logging in to Dooker...
            - docker login --username tenthinc2 --password 84d4ba4d-5178-4928-9f7f-d8a4be9294d1
            - REPOSITORY_URI=965522962451.dkr.ecr.ap-northeast-2.amazonaws.com/skyshop/front
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_TAG=${COMMIT_HASH:=latest}
    build:
        commands:
            - docker build -t skyshop/front .
    post_build:
        commands:
            - docker tag skyshop/front:latest $REPOSITORY_URI:latest
            - docker push $REPOSITORY_URI:latest
            - echo Writing image definitions file...
            - printf '[{"name":"skyshopFrontContainer","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
