import { Html, Head, Main, NextScript } from 'next/document';
import Script from 'next/script';

export default function Document() {
  return (
    <Html>
      <Head />
      <title>대한항공 면세점</title>
      <meta name="description" content="Generated by create next app  " />
      <link rel="icon" href="/favicon.ico" />

      <link
        href="https://fonts.googleapis.com/css2?family=Baskervville:ital@0;1&display=swap"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap"
        rel="stylesheet"
      ></link>
      <script
        src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"
        defer
      ></script>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
